import { ObjectId, type WithId } from "mongodb";

export type GoalRecord = { userId: string; title: string; description: string; successCriteria: string; priority: "low" | "medium" | "high"; status: "not_started" | "in_progress" | "completed" | "archived"; targetDate: Date | null; createdAt: Date; updatedAt: Date; completedAt: Date | null; archivedAt: Date | null };
export type MilestoneRecord = { userId: string; goalId: ObjectId; title: string; description: string; targetDate: Date | null; status: "not_started" | "in_progress" | "completed"; order: number; createdAt: Date; updatedAt: Date; completedAt: Date | null };
export type TaskRecord = { userId: string; goalId: ObjectId; milestoneId: ObjectId | null; title: string; description: string; status: "todo" | "in_progress" | "completed" | "blocked"; priority: "low" | "medium" | "high"; dueDate: Date | null; plannedDate: Date | null; estimatedMinutes: number; blockedReason: string | null; deferCount: number; createdAt: Date; updatedAt: Date; completedAt: Date | null };
export type FocusSessionRecord = { userId: string; taskId: ObjectId; startedAt: Date; endedAt: Date | null };
export type UserRecord = { clerkUserId: string; displayName: string; email: string; onboardingCompleted: boolean; planning: { dailyAvailableMinutes: number; defaultFocusMinutes: number; workingDays: number[]; workStyle: "short" | "balanced" | "deep" }; notifications: { goalCompleted: boolean; milestoneCompleted: boolean; planningReminders: boolean }; createdAt: Date; updatedAt: Date };

const iso = (value: Date | null) => value?.toISOString() ?? null;
export const serializeGoal = (r: WithId<GoalRecord>) => ({ id: r._id.toHexString(), userId: r.userId, title: r.title, description: r.description, successCriteria: r.successCriteria, priority: r.priority, status: r.status, targetDate: iso(r.targetDate), createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString(), completedAt: iso(r.completedAt), archivedAt: iso(r.archivedAt) });
export const serializeMilestone = (r: WithId<MilestoneRecord>) => ({ id: r._id.toHexString(), userId: r.userId, goalId: r.goalId.toHexString(), title: r.title, description: r.description, targetDate: iso(r.targetDate), status: r.status, order: r.order, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString(), completedAt: iso(r.completedAt) });
export const serializeTask = (r: WithId<TaskRecord>) => ({ id: r._id.toHexString(), userId: r.userId, goalId: r.goalId.toHexString(), milestoneId: r.milestoneId?.toHexString() ?? null, title: r.title, description: r.description, status: r.status, priority: r.priority, dueDate: iso(r.dueDate), plannedDate: iso(r.plannedDate), estimatedMinutes: r.estimatedMinutes, blockedReason: r.blockedReason, deferCount: r.deferCount, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString(), completedAt: iso(r.completedAt) });
